// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ping.proto

package model.proto;

public final class Ping {
  private Ping() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface PingRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:model.PingRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string id = 1;</code>
     */
    boolean hasId();
    /**
     * <code>required string id = 1;</code>
     */
    java.lang.String getId();
    /**
     * <code>required string id = 1;</code>
     */
    com.google.protobuf.ByteString
        getIdBytes();

    /**
     * <code>optional int64 now = 2;</code>
     */
    boolean hasNow();
    /**
     * <code>optional int64 now = 2;</code>
     */
    long getNow();
  }
  /**
   * Protobuf type {@code model.PingRequest}
   */
  public static final class PingRequest extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:model.PingRequest)
      PingRequestOrBuilder {
    // Use PingRequest.newBuilder() to construct.
    private PingRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private PingRequest(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final PingRequest defaultInstance;
    public static PingRequest getDefaultInstance() {
      return defaultInstance;
    }

    public PingRequest getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private PingRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              id_ = bs;
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              now_ = input.readInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return model.proto.Ping.internal_static_model_PingRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return model.proto.Ping.internal_static_model_PingRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              model.proto.Ping.PingRequest.class, model.proto.Ping.PingRequest.Builder.class);
    }

    public static com.google.protobuf.Parser<PingRequest> PARSER =
        new com.google.protobuf.AbstractParser<PingRequest>() {
      public PingRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new PingRequest(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<PingRequest> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int ID_FIELD_NUMBER = 1;
    private java.lang.Object id_;
    /**
     * <code>required string id = 1;</code>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string id = 1;</code>
     */
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          id_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string id = 1;</code>
     */
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int NOW_FIELD_NUMBER = 2;
    private long now_;
    /**
     * <code>optional int64 now = 2;</code>
     */
    public boolean hasNow() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional int64 now = 2;</code>
     */
    public long getNow() {
      return now_;
    }

    private void initFields() {
      id_ = "";
      now_ = 0L;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt64(2, now_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, now_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static model.proto.Ping.PingRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static model.proto.Ping.PingRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static model.proto.Ping.PingRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static model.proto.Ping.PingRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static model.proto.Ping.PingRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static model.proto.Ping.PingRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static model.proto.Ping.PingRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static model.proto.Ping.PingRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static model.proto.Ping.PingRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static model.proto.Ping.PingRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(model.proto.Ping.PingRequest prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code model.PingRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:model.PingRequest)
        model.proto.Ping.PingRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return model.proto.Ping.internal_static_model_PingRequest_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return model.proto.Ping.internal_static_model_PingRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                model.proto.Ping.PingRequest.class, model.proto.Ping.PingRequest.Builder.class);
      }

      // Construct using model.proto.Ping.PingRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        id_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        now_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return model.proto.Ping.internal_static_model_PingRequest_descriptor;
      }

      public model.proto.Ping.PingRequest getDefaultInstanceForType() {
        return model.proto.Ping.PingRequest.getDefaultInstance();
      }

      public model.proto.Ping.PingRequest build() {
        model.proto.Ping.PingRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public model.proto.Ping.PingRequest buildPartial() {
        model.proto.Ping.PingRequest result = new model.proto.Ping.PingRequest(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.now_ = now_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof model.proto.Ping.PingRequest) {
          return mergeFrom((model.proto.Ping.PingRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(model.proto.Ping.PingRequest other) {
        if (other == model.proto.Ping.PingRequest.getDefaultInstance()) return this;
        if (other.hasId()) {
          bitField0_ |= 0x00000001;
          id_ = other.id_;
          onChanged();
        }
        if (other.hasNow()) {
          setNow(other.getNow());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasId()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        model.proto.Ping.PingRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (model.proto.Ping.PingRequest) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object id_ = "";
      /**
       * <code>required string id = 1;</code>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string id = 1;</code>
       */
      public java.lang.String getId() {
        java.lang.Object ref = id_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            id_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string id = 1;</code>
       */
      public com.google.protobuf.ByteString
          getIdBytes() {
        java.lang.Object ref = id_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          id_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string id = 1;</code>
       */
      public Builder setId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string id = 1;</code>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = getDefaultInstance().getId();
        onChanged();
        return this;
      }
      /**
       * <code>required string id = 1;</code>
       */
      public Builder setIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }

      private long now_ ;
      /**
       * <code>optional int64 now = 2;</code>
       */
      public boolean hasNow() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional int64 now = 2;</code>
       */
      public long getNow() {
        return now_;
      }
      /**
       * <code>optional int64 now = 2;</code>
       */
      public Builder setNow(long value) {
        bitField0_ |= 0x00000002;
        now_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 now = 2;</code>
       */
      public Builder clearNow() {
        bitField0_ = (bitField0_ & ~0x00000002);
        now_ = 0L;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:model.PingRequest)
    }

    static {
      defaultInstance = new PingRequest(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:model.PingRequest)
  }

  public interface PingResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:model.PingResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required .model.PingRequest pingRequest = 1;</code>
     */
    boolean hasPingRequest();
    /**
     * <code>required .model.PingRequest pingRequest = 1;</code>
     */
    model.proto.Ping.PingRequest getPingRequest();
    /**
     * <code>required .model.PingRequest pingRequest = 1;</code>
     */
    model.proto.Ping.PingRequestOrBuilder getPingRequestOrBuilder();

    /**
     * <code>optional int64 latency = 2;</code>
     */
    boolean hasLatency();
    /**
     * <code>optional int64 latency = 2;</code>
     */
    long getLatency();
  }
  /**
   * Protobuf type {@code model.PingResponse}
   */
  public static final class PingResponse extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:model.PingResponse)
      PingResponseOrBuilder {
    // Use PingResponse.newBuilder() to construct.
    private PingResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private PingResponse(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final PingResponse defaultInstance;
    public static PingResponse getDefaultInstance() {
      return defaultInstance;
    }

    public PingResponse getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private PingResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              model.proto.Ping.PingRequest.Builder subBuilder = null;
              if (((bitField0_ & 0x00000001) == 0x00000001)) {
                subBuilder = pingRequest_.toBuilder();
              }
              pingRequest_ = input.readMessage(model.proto.Ping.PingRequest.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(pingRequest_);
                pingRequest_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000001;
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              latency_ = input.readInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return model.proto.Ping.internal_static_model_PingResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return model.proto.Ping.internal_static_model_PingResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              model.proto.Ping.PingResponse.class, model.proto.Ping.PingResponse.Builder.class);
    }

    public static com.google.protobuf.Parser<PingResponse> PARSER =
        new com.google.protobuf.AbstractParser<PingResponse>() {
      public PingResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new PingResponse(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<PingResponse> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int PINGREQUEST_FIELD_NUMBER = 1;
    private model.proto.Ping.PingRequest pingRequest_;
    /**
     * <code>required .model.PingRequest pingRequest = 1;</code>
     */
    public boolean hasPingRequest() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .model.PingRequest pingRequest = 1;</code>
     */
    public model.proto.Ping.PingRequest getPingRequest() {
      return pingRequest_;
    }
    /**
     * <code>required .model.PingRequest pingRequest = 1;</code>
     */
    public model.proto.Ping.PingRequestOrBuilder getPingRequestOrBuilder() {
      return pingRequest_;
    }

    public static final int LATENCY_FIELD_NUMBER = 2;
    private long latency_;
    /**
     * <code>optional int64 latency = 2;</code>
     */
    public boolean hasLatency() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional int64 latency = 2;</code>
     */
    public long getLatency() {
      return latency_;
    }

    private void initFields() {
      pingRequest_ = model.proto.Ping.PingRequest.getDefaultInstance();
      latency_ = 0L;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasPingRequest()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!getPingRequest().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeMessage(1, pingRequest_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt64(2, latency_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, pingRequest_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, latency_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static model.proto.Ping.PingResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static model.proto.Ping.PingResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static model.proto.Ping.PingResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static model.proto.Ping.PingResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static model.proto.Ping.PingResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static model.proto.Ping.PingResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static model.proto.Ping.PingResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static model.proto.Ping.PingResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static model.proto.Ping.PingResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static model.proto.Ping.PingResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(model.proto.Ping.PingResponse prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code model.PingResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:model.PingResponse)
        model.proto.Ping.PingResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return model.proto.Ping.internal_static_model_PingResponse_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return model.proto.Ping.internal_static_model_PingResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                model.proto.Ping.PingResponse.class, model.proto.Ping.PingResponse.Builder.class);
      }

      // Construct using model.proto.Ping.PingResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getPingRequestFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (pingRequestBuilder_ == null) {
          pingRequest_ = model.proto.Ping.PingRequest.getDefaultInstance();
        } else {
          pingRequestBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        latency_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return model.proto.Ping.internal_static_model_PingResponse_descriptor;
      }

      public model.proto.Ping.PingResponse getDefaultInstanceForType() {
        return model.proto.Ping.PingResponse.getDefaultInstance();
      }

      public model.proto.Ping.PingResponse build() {
        model.proto.Ping.PingResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public model.proto.Ping.PingResponse buildPartial() {
        model.proto.Ping.PingResponse result = new model.proto.Ping.PingResponse(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        if (pingRequestBuilder_ == null) {
          result.pingRequest_ = pingRequest_;
        } else {
          result.pingRequest_ = pingRequestBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.latency_ = latency_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof model.proto.Ping.PingResponse) {
          return mergeFrom((model.proto.Ping.PingResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(model.proto.Ping.PingResponse other) {
        if (other == model.proto.Ping.PingResponse.getDefaultInstance()) return this;
        if (other.hasPingRequest()) {
          mergePingRequest(other.getPingRequest());
        }
        if (other.hasLatency()) {
          setLatency(other.getLatency());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasPingRequest()) {
          
          return false;
        }
        if (!getPingRequest().isInitialized()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        model.proto.Ping.PingResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (model.proto.Ping.PingResponse) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private model.proto.Ping.PingRequest pingRequest_ = model.proto.Ping.PingRequest.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          model.proto.Ping.PingRequest, model.proto.Ping.PingRequest.Builder, model.proto.Ping.PingRequestOrBuilder> pingRequestBuilder_;
      /**
       * <code>required .model.PingRequest pingRequest = 1;</code>
       */
      public boolean hasPingRequest() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .model.PingRequest pingRequest = 1;</code>
       */
      public model.proto.Ping.PingRequest getPingRequest() {
        if (pingRequestBuilder_ == null) {
          return pingRequest_;
        } else {
          return pingRequestBuilder_.getMessage();
        }
      }
      /**
       * <code>required .model.PingRequest pingRequest = 1;</code>
       */
      public Builder setPingRequest(model.proto.Ping.PingRequest value) {
        if (pingRequestBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          pingRequest_ = value;
          onChanged();
        } else {
          pingRequestBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .model.PingRequest pingRequest = 1;</code>
       */
      public Builder setPingRequest(
          model.proto.Ping.PingRequest.Builder builderForValue) {
        if (pingRequestBuilder_ == null) {
          pingRequest_ = builderForValue.build();
          onChanged();
        } else {
          pingRequestBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .model.PingRequest pingRequest = 1;</code>
       */
      public Builder mergePingRequest(model.proto.Ping.PingRequest value) {
        if (pingRequestBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001) &&
              pingRequest_ != model.proto.Ping.PingRequest.getDefaultInstance()) {
            pingRequest_ =
              model.proto.Ping.PingRequest.newBuilder(pingRequest_).mergeFrom(value).buildPartial();
          } else {
            pingRequest_ = value;
          }
          onChanged();
        } else {
          pingRequestBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .model.PingRequest pingRequest = 1;</code>
       */
      public Builder clearPingRequest() {
        if (pingRequestBuilder_ == null) {
          pingRequest_ = model.proto.Ping.PingRequest.getDefaultInstance();
          onChanged();
        } else {
          pingRequestBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      /**
       * <code>required .model.PingRequest pingRequest = 1;</code>
       */
      public model.proto.Ping.PingRequest.Builder getPingRequestBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getPingRequestFieldBuilder().getBuilder();
      }
      /**
       * <code>required .model.PingRequest pingRequest = 1;</code>
       */
      public model.proto.Ping.PingRequestOrBuilder getPingRequestOrBuilder() {
        if (pingRequestBuilder_ != null) {
          return pingRequestBuilder_.getMessageOrBuilder();
        } else {
          return pingRequest_;
        }
      }
      /**
       * <code>required .model.PingRequest pingRequest = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          model.proto.Ping.PingRequest, model.proto.Ping.PingRequest.Builder, model.proto.Ping.PingRequestOrBuilder> 
          getPingRequestFieldBuilder() {
        if (pingRequestBuilder_ == null) {
          pingRequestBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              model.proto.Ping.PingRequest, model.proto.Ping.PingRequest.Builder, model.proto.Ping.PingRequestOrBuilder>(
                  getPingRequest(),
                  getParentForChildren(),
                  isClean());
          pingRequest_ = null;
        }
        return pingRequestBuilder_;
      }

      private long latency_ ;
      /**
       * <code>optional int64 latency = 2;</code>
       */
      public boolean hasLatency() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional int64 latency = 2;</code>
       */
      public long getLatency() {
        return latency_;
      }
      /**
       * <code>optional int64 latency = 2;</code>
       */
      public Builder setLatency(long value) {
        bitField0_ |= 0x00000002;
        latency_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 latency = 2;</code>
       */
      public Builder clearLatency() {
        bitField0_ = (bitField0_ & ~0x00000002);
        latency_ = 0L;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:model.PingResponse)
    }

    static {
      defaultInstance = new PingResponse(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:model.PingResponse)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_model_PingRequest_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_model_PingRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_model_PingResponse_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_model_PingResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nping.proto\022\005model\"&\n\013PingRequest\022\n\n\002id" +
      "\030\001 \002(\t\022\013\n\003now\030\002 \001(\003\"H\n\014PingResponse\022\'\n\013p" +
      "ingRequest\030\001 \002(\0132\022.model.PingRequest\022\017\n\007" +
      "latency\030\002 \001(\003B\023\n\013model.protoB\004Ping"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_model_PingRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_model_PingRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_model_PingRequest_descriptor,
        new java.lang.String[] { "Id", "Now", });
    internal_static_model_PingResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_model_PingResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_model_PingResponse_descriptor,
        new java.lang.String[] { "PingRequest", "Latency", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
